<a href="https://colab.research.google.com/github/SubhamMohanty187/PythonPractice/blob/main/PythonPractice3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
import numpy as np

In [2]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [3]:
type(my_lst)

list

In [4]:
type(arr)

numpy.ndarray

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [7]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [8]:
arr.shape  # rows x cols

(3, 5)

In [9]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [10]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [11]:
arr[:2, :2]

array([[1, 2],
       [2, 3]])

In [12]:
arr[1: , 3:]

array([[5, 6],
       [8, 9]])

In [13]:
arr[1: , 2:4]

array([[4, 5],
       [6, 8]])

In [14]:
arr[1:2 , 1:4 ]

array([[3, 4, 5]])

In [15]:
arr = np.arange(0,10)

In [16]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr = np.linspace(0, 10, 20)
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [18]:
import pandas as pd

In [19]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4), index=['Row1','Row2','Row3','Row4','Row5'], columns=['column1', 'column2', 'column3', 'column4'])
df

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [20]:
# Converting dataframe to arrays
df.iloc[: , :].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

Reading Data from String format.

In [22]:
 from io import StringIO
 data = ('a,b,c\n'
           '4,apple,bat,\n'
            '8,orange,cow,')


In [25]:
df = pd.read_csv(StringIO(data), index_col=False)
df

a       b    c
0  4   apple  bat
1  8  orange  cow

In [27]:
## Quoting and Escape Characters¶. Very useful in NLP

data = 'a,b\n"hello, \\"Bob\\", nice to see you",5'

In [29]:
df = pd.read_csv(StringIO(data), escapechar='\\')
df

a  b
0  hello, "Bob", nice to see you  5

In [ ]:
## URL to CSV
url = 'https://download.bls.gov/pub/time.series/cu/cu.item'
df=pd.read_csv(url, sep='\t')
df

Json To CSV

In [35]:
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
df = pd.read_json(Data)
df

employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [36]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)

In [37]:
df.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [38]:
df.to_csv('wine.csv')

Reading HTML

In [41]:
url = 'https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/'

dfs = pd.read_html(url)
dfs[0]

Bank NameBank       CityCity StateSt  CertCert  \
0    Republic First Bank dba Republic Bank   Philadelphia      PA     27332   
1                            Citizens Bank       Sac City      IA      8758   
2                 Heartland Tri-State Bank        Elkhart      KS     25851   
3                      First Republic Bank  San Francisco      CA     59017   
4                           Signature Bank       New York      NY     57053   
..                                     ...            ...     ...       ...   
564                     Superior Bank, FSB       Hinsdale      IL     32646   
565                    Malta National Bank          Malta      OH      6629   
566        First Alliance Bank & Trust Co.     Manchester      NH     34264   
567      National State Bank of Metropolis     Metropolis      IL      3815   
568                       Bank of Honolulu       Honolulu      HI     21029   

                 Acquiring InstitutionAI Closing DateClosing  FundFund  
0      Fulton Bank, National Association      April 26, 2024     10546  
1              Iowa Trust & Savings Bank    November 3, 2023     10545  
2                 Dream First Bank, N.A.       July 28, 2023     10544  
3              JPMorgan Chase Bank, N.A.         May 1, 2023     10543  
4                    Flagstar Bank, N.A.      March 12, 2023     10540  
..                                   ...                 ...       ...  
564                Superior Federal, FSB       July 27, 2001      6004  
565                    North Valley Bank         May 3, 2001      4648  
566  Southern New Hampshire Bank & Trust    February 2, 2001      4647  
567              Banterra Bank of Marion   December 14, 2000      4646  
568                   Bank of the Orient    October 13, 2000      4645  

[569 rows x 7 columns]

##Pickling
All pandas objects are equipped with to_pickle methods which use Python’s cPickle module to save data structures to disk using the pickle format.

In [42]:
dfs[0].to_pickle('dfs[0]')

In [44]:
df = pd.read_pickle('dfs[0]')
df

Bank NameBank       CityCity StateSt  CertCert  \
0    Republic First Bank dba Republic Bank   Philadelphia      PA     27332   
1                            Citizens Bank       Sac City      IA      8758   
2                 Heartland Tri-State Bank        Elkhart      KS     25851   
3                      First Republic Bank  San Francisco      CA     59017   
4                           Signature Bank       New York      NY     57053   
..                                     ...            ...     ...       ...   
564                     Superior Bank, FSB       Hinsdale      IL     32646   
565                    Malta National Bank          Malta      OH      6629   
566        First Alliance Bank & Trust Co.     Manchester      NH     34264   
567      National State Bank of Metropolis     Metropolis      IL      3815   
568                       Bank of Honolulu       Honolulu      HI     21029   

                 Acquiring InstitutionAI Closing DateClosing  FundFund  
0      Fulton Bank, National Association      April 26, 2024     10546  
1              Iowa Trust & Savings Bank    November 3, 2023     10545  
2                 Dream First Bank, N.A.       July 28, 2023     10544  
3              JPMorgan Chase Bank, N.A.         May 1, 2023     10543  
4                    Flagstar Bank, N.A.      March 12, 2023     10540  
..                                   ...                 ...       ...  
564                Superior Federal, FSB       July 27, 2001      6004  
565                    North Valley Bank         May 3, 2001      4648  
566  Southern New Hampshire Bank & Trust    February 2, 2001      4647  
567              Banterra Bank of Marion   December 14, 2000      4646  
568                   Bank of the Orient    October 13, 2000      4645  

[569 rows x 7 columns]